@project_id = 6078
@member_id = 310
### Add Project Manager
PATCH {{baseUrl}}/project/projects/{{project_id}}
Authorization: Basic {{companyid}}+{{publicKey}} {{privateKey}}
clientId: {{clientid}}
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/manager",
        "value": {
            "id": {{member_id}}
        }
    }
]
