@company_name = Test Company
### Get Invoices for a Company
GET {{baseUrl}}/finance/invoices
    ?conditions=company/name='{{company_name}}'
Authorization: Basic {{companyid}}+{{publicKey}} {{privateKey}}
clientId: {{clientid}}
