POST https://api.cloudflare.com/client/v4/graphql
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "query": "{ viewer { zones(filter: {zoneTag: \"{{zonetag}}\"}) { httpRequests1dGroups(filter: {date_gt: \"2024-12-01\"}, limit: 1) { uniq { uniques } } } } }"
}